name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ny_taxi_app:$(date +%s)
    - name: Push to GHCR
      uses: GlueOps/github-actions-build-push-containers@0.3.5

